### PR TITLE
Resolve race condition in feature flag duplication flow

### LINKED ISSUE #2520: Progress bar continues on feature flag duplication
**Version where bug was found:**
6.1

**Describe the bug**
When you duplicate a feature flag, the progress bars on the lists do not stop

**To Reproduce**
1. Go to a feature flag details page
2. Click on 'Duplicate Feature Flag'
3. Choose a name and click 'Add'

**Expected behavior**
The call to /flags/:flagID should succed, and the progress bars should not keep going.

**Additional context**
Possibly introduced by this PR: https://github.com/CarnegieLearningWeb/UpGrade/pull/2514

### PR DESCRIPTION
**Pull request by zackcl**
## Problem
When duplicating a feature flag, progress bars would continue spinning indefinitely after clicking "Add" in the duplicate modal. The API call to fetch the newly created flag (`GET /api/flags/:flagId`) was failing because it was being called before the backend had fully persisted the duplicated flag.

## Root Cause
**Race condition between navigation and data fetching:**
- Feature flag details component was fetching the flag immediately when route params changed
- This happened before navigation was complete, causing the fetch to occur before the backend had persisted the new flag
- Unlike segments (which work correctly), feature flags weren't waiting for navigation completion

### 1. Component Fix (Primary)
- Updated `FeatureFlagDetailsPageContentComponent` to wait for navigation completion before fetching
- Added `combineLatest([routeParams$, navigationComplete$])` pattern to ensure fetch only happens after navigation ends
- Matches the working pattern used in `SegmentDetailsPageComponent`

### 2. Effects Refactoring (Code Quality)
- Separated navigation logic from HTTP operations in `feature-flags.effects.ts`
- Created dedicated `navigateToFeatureFlagDetail$` effect following NgRx best practices
- Ensures consistency with segments effects pattern

## Testing
- [x] Duplicate feature flag → progress bars stop correctly
- [x] Navigate to flag details → loads properly
- [x] No regression in existing functionality

Closes #2520

### CODE REVIEW

File: frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-details-page/feature-flag-details-page-content/feature-flag-details-page-content.component.ts [hunk 1]
```diff
@@ -6,11 +6,12 @@ import { FeatureFlagExclusionsSectionCardComponent } from './feature-flag-exclus
 import { FeatureFlagExposuresSectionCardComponent } from './feature-flag-exposures-section-card/feature-flag-exposures-section-card.component';
 import { FeatureFlagOverviewDetailsSectionCardComponent } from './feature-flag-overview-details-section-card/feature-flag-overview-details-section-card.component';
 import { FeatureFlagsService } from '../../../../../../core/feature-flags/feature-flags.service';
-import { Observable, Subscription } from 'rxjs';
+import { Observable, Subscription, combineLatest } from 'rxjs';
 import { FeatureFlag } from '../../../../../../core/feature-flags/store/feature-flags.model';
-import { ActivatedRoute } from '@angular/router';
+import { ActivatedRoute, NavigationEnd, Router } from '@angular/router';
 import { SharedModule } from '../../../../../../shared/shared.module';
```
Comment (bcb37) [inline frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-details-page/feature-flag-details-page-content/feature-flag-details-page-content.component.ts:12]: What's the purpose of `SharedModule`? I noticed that if I removed that from 'CommonDetailsParticipantListTableComponent' if fixed this problem, and didn't result in any other problems - but I probably didn't see them.

**Review by bcb37 — COMMENTED** [review]
This seems to work. Just one question.
