### PR TITLE
(Analytics Controller) Issues in sending csv email and adding proper error codes and swagger improvements

### LINKED ISSUE #1733: Analytics Controller Swagger and Email send bugs and improvements
**Version where bug was found:**
e.g "5.2.0"

**Describe the bug**
Need to add various swagger error codes in Analytics Controller and sending proper http codes for email send error. Also, there is an error of "Missing final '@domain'" due to comma in EMAIL_FROM env variable.

### PR DESCRIPTION
**Pull request by ppratikcr7**
Sending proper error codes in api response (500 instead of 400) for sending email and error code coverage in analytics controller swagger doc.
There was an error of "Missing final '@ domain'" due to a comma after the email id in env file. This PR resolves #1733 
Screenshot 2024-07-05 at 6 52 17 PM

### CODE REVIEW

File: backend/packages/Upgrade/src/api/services/AnalyticsService.ts [hunk 1]
```diff
@@ -431,13 +431,23 @@ export class AnalyticsService {
...
       // send email to the user
       logger.info({ message: `Sending export data email to ${email}` });
-      await this.awsService.sendEmail(email_from, email, emailText, emailSubject);
-      await this.experimentAuditLogRepository.saveRawJson(
-        EXPERIMENT_LOG_TYPE.EXPERIMENT_DATA_EXPORTED,
-        { experimentName: experimentQueryResult[0].experimentName },
-        user
-      );
-      logger.info({ message: `Exported Data emailed successfully to ${email}` });
+      try {
```
Comment (VivekFitkariwala) [inline backend/packages/Upgrade/src/api/services/AnalyticsService.ts:434]: Try catch should only wrap `sendEmail` function

**Review by VivekFitkariwala — CHANGES_REQUESTED** [review]

**Comment by danoswaltCL** [comment]
@VivekFitkariwala can we get an updated review on this so we can move towards resolving some of our older PRs?

**Review by VivekFitkariwala — APPROVED** [review]
