### PR TITLE
fix order of payloads returned with experiments

### LINKED ISSUE #2845: Payloads table row order changes unexpectedly after experiment updates
The order of rows in the Payloads table changes randomly immediately after updating the experiment.

### PR DESCRIPTION
**Pull request by bcb37**

### CODE REVIEW

File: backend/packages/Upgrade/src/api/services/ExperimentService.ts [hunk 1]
```diff
@@ -1065,6 +1065,14 @@ export class ExperimentService {
...
         });
 
+        // sort the payloads by decision point order and condition order
+        conditionPayloadDocToReturn.sort((a, b) => {
+          if (a.decisionPoint.order === b.decisionPoint.order) {
+            return a.parentCondition.order - b.parentCondition.order;
+          }
+          return a.decisionPoint.order - b.decisionPoint.order;
+        });
+
```
Comment (danoswaltCL) [inline backend/packages/Upgrade/src/api/services/ExperimentService.ts:1075]: both conditions are returning same thing, `a.decisionPoint.order - b.decisionPoint.order`

```suggestion
        // sort the payloads by decision point order and condition order
        conditionPayloadDocToReturn.sort((a, b) => {
          return a.decisionPoint.order - b.decisionPoint.order;
        });

```

Comment (bcb37) [reply backend/packages/Upgrade/src/api/services/ExperimentService.ts:1075]: @danoswaltCL  I'm not sure I understand. If `decisionPoint.order` is the same for both, then we return sorted by `parentCondition.order`, otherwise we return sorted by `decisionPoint.order`.
Am I missing something?

Comment (danoswaltCL) [reply backend/packages/Upgrade/src/api/services/ExperimentService.ts:1075]: no, i can't read good

**Review by danoswaltCL — APPROVED** [review]
